### ISSUE TITLE
Installation impossible due to dependency on bundle org.eclipse.ui.trace

### ISSUE THREAD

**Issue by baldapps** [15knots/cmake4eclipse#127]
Installation offline doesn't work using Eclipse (with CDT). cmake4eclipse requires org.eclipse.ui.trace. Is the dependency from PDE needed to install cmake4eclipse?

**Comment by 15knots** [comment]
Thanks for reporting this.
Actually, I wasn't aware that it is a dependency to PDE.
Please file an issue at the github site.


Am Di., 7. Jan. 2020 um 11:12 Uhr schrieb baldapps <notifications@github.com

**Comment by baldapps** [comment]
I'm confused, we are already on GitHub, are you talking about another site??
Dependency is in plug-in.xml

<extension
       point="org.eclipse.ui.trace.traceComponents">
    <component
          id="de.marw.cmake.trace"
          label="Cmake4eclipse CDT indexer support">
       <bundle
             name="de.marw.cmake">
       </bundle>
    </component>
 </extension>

**Comment by 15knots** [comment]
Will have to revert the change that fixed the dependency.

I tested it with a fresh installation of Eclipse CDT 2019-12 product and found the following after installing cmake4eclipse:
- Without the dependency on bundle org.eclipse.ui.trace, the plugin's tracing option will not show up in the workbench tracing preferences.
- If the dependency on bundle org.eclipse.ui.trace (or one of its exported packages) is  **optional** , the workbench will no longer display the _Tracing_ preferences node.

So, to quote

> Is the dependency from PDE needed to install cmake4eclipse?

I would answer yes here.

Since the eclipse CDT product comes with bundle org.eclipse.ui.trace installed, I am wondering why you get the install error.

**Comment by baldapps** [comment]
> Will have to revert the change that fixed the dependency.
> 
> I tested it with a fresh installation of Eclipse CDT 2019-12 product and found the following after installing cmake4eclipse:
> 
> * Without the dependency on bundle org.eclipse.ui.trace, the plugin's tracing option will not show up in the workbench tracing preferences.
> * If the dependency on bundle org.eclipse.ui.trace (or one of its exported packages) is  **optional** , the workbench will no longer display the _Tracing_ preferences node.
> 
> So, to quote
> 
> > Is the dependency from PDE needed to install cmake4eclipse?
> 
> I would answer yes here.
> 
> Since the eclipse CDT product comes with bundle org.eclipse.ui.trace installed, I am wondering why you get the install error.

No idea, I just downloaded Eclipse C/C++ developer bundle from download website, 2019-12, and move it in a workstation without internet access. I didn't do it anything more.

**Comment by 15knots** [comment]
The CDT download zip file indeed does not contain bundle org.eclipse.ui.trace. That bundle is automatically downloaded from remote repos when you install cmake4eclipse.
I did not notice that since I **have** network access.
