### ISSUE TITLE
cmake4eclipse API doc and how to perform generator only function via API

### ISSUE THREAD

**Issue by xmnboy** [15knots/cmake4eclipse#132]
**On project creation we would like to initiate a CMake generator run without a build step.**

We are creating projects from samples that have multiple Makefile targets. We have an Eclipse plugin that manages creation of these sample projects. Most are CMake projects that are configured to utilize `cmake4eclipse` and Eclipse CDT. 

We would like to be able to trigger `cmake4eclipse` upon creation of the sample project, but only want it to perform the generator step, we do not want to have it also perform a `make all` step. Is there a way to do this programmatically?

These CMake build files will generate multiple Makefile build targets. We are utilizing the Eclipse CDT "Build Targets" feature that is provided for use with Makefile projects to display the custom targets defined in the resulting Makefile in order to make it easier for our developers to find and execute these custom Makefile targets.

**Comment by xmnboy** [comment]
An alternative approach would be to provide a way to programmatically request a CMake generation _plus_ a make build operation; that is, we can specify the make build target when requesting a CMake run.

**Comment by 15knots** [comment]
Buildscript generation is in `de.marw.cdt.cmake.core.internal.BuildscriptGenerator`. That class implements IManagedBuilderMakefileGenerator2. To run build script generation, first call `initialize(int buildKind, IConfiguration cfg, IBuilder builder, IProgressMonitor monitor)` and then `generateMakefiles()`.
Unfortunately `BuildscriptGenerator` is not public API. Maybe you will be able to retrieve an instance by loading the extension point `org.eclipse.cdt.managedbuilder.core.buildDefinitions` programmatically, but I did not try that ever.

A different approach would be to provide a No-Op build-runner and configure each project to use that build-runner instead of the default `de.marw.cdt.cmake.core.internal.CMakeBuildRunner`.
Cmake4eclipse will then generate the scripts on the first build (IMHO that could be triggered programatically). After build-script-generation, CDT will call your No-Op buildrunner.

**Comment by xmnboy** [comment]
Thank you, @15knots (Martin). We'll see if we can make something work with your suggestion, above.
