### ISSUE TITLE
CmakePresets integration

### ISSUE THREAD

**Issue by ToBoMi** [15knots/cmake4eclipse#175]
**Is your feature request related to a problem? Please describe.**
I have a project which relies on a `CMakePresets.json` ([IDE Integration Guide](https://cmake.org/cmake/help/latest/guide/ide-integration/index.html#presets)). I cannot see something related to CMakePresets in this project and I assume it is surrently not supported, right?

**Describe the solution you'd like**
The CMakePresets file is recognized (by eclipse or this addon) and its definitions are set in the internal memory of the IDE at the appropriate places. (CMakeCache, Environmental Variables)
Currently the definitions of the file are simply not used and are missing during cmake execution.

**Describe alternatives you've considered**
I might be able to completely define these variables myself by hand using the existing options in cmake4eclipse, but I have not been successful with all of them. I remember, that I was able to set a single cmake cache entry of the presets file successfully. This is not ideal, because in the CMakePresets file the build configurations are defined. In cmake4eclipse also build configurations are defined (Debug, Release - eclipse build configurations) and they should correspond. Can I change the build configurations in eclipse and adopt them to match the ones in the CMakePresets? (Maybe a separate issue)

**Additional context**
I am not allowed to share the contents of that project, but if needed I might find another project that uses CMakePresets.

**Comment by 15knots** [comment]
The plugin does not read nor interpret any of the files that control the operation of cmake (CMakeLists.txt, presets.json etc.). It simply calls cmake with the apropiate source directory argument in the build directory. So it does not make sense to interprete any presets.json files.

So you are actually asking to support the `--presets` arguments of cmake?

**Comment by TobiasBoeschMiele** [comment]
>The plugin does not read nor interpret any of the files that control the operation of cmake (CMakeLists.txt, presets.json etc.).

Good to know thanks.

>It simply calls cmake with the apropiate source directory argument in the build directory. So it does not make sense to interprete any presets.json files.

Okay.
I see it like this: If these files are not interpreted (when they are present), then the execution of cmake does not makes sense. The reason is that in those files there are some cmake-definitions made which are used inside the `CMakeLists.txt` files.
This is a problem I currently cannot get around when using eclipse with this plugin. (Except I manually define all these variables in this plugin somehow - so that cmake knows all the definitions when it is called).

>So you are actually asking to support the --presets arguments of cmake?

That would work, but is not recommended as mentioned in the [IDE Integration Guide](https://cmake.org/cmake/help/latest/guide/ide-integration/index.html#presets):

>The --preset= option is intended only as a convenient frontend for command line users, and should not be used by the IDE.

I think they say this because things that are defined in that file might be of interest to other tools inside the IDE. My current `CMakePresets.json` file contains (beside other things):

```
[...]
      "CMAKE_BUILD_TYPE": "Debug"
[...]
```

This might be of interest to the indexer of eclipse.

**Comment by TobiasBoeschMiele** [comment]
Another thing that is defined in these files are `configurations` (see [cmake-presets(7)](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#id1)[¶](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html#cmake-presets-7))

I would expect that the cmake support in eclipse shows the existing configuration in the UI somehow so that one can select the configuration to build from the UI. I don't know how to select another build configuration /target from this plugin.

**Comment by elupus** [comment]
A plus one for us. We (www.rt-labs.com) build embedded systems and we make extensive use of presets to specify toolchain file locations and options for the build environment. Just directly calling cmake on the project does not work, it needs parameters specified to work and specify them manually quickly become complicated.

**Comment by 15knots** [comment]
IMHO, it would be hard to fully support the set of features provided by cmake presets in CDT managed build (the base of cmake4eclipse).
Some things that come to my mind here are:
1. Mapping of different configurations in the presets file vs. configurations defined in/for CDT managed build system (MBS). The MBS UI only allows users to create a build configuration that is predefined in one of its plugins through an eclipse extension point. I do not see a way to add an option to the MBS UI for users to create a new configuration by importing it from a presets file.
2. Absolute output directory specified in the presets file. The output directory **must** be relative to the project root (it **must** be an Eclipse resource) in order to provide proper error messages for cmake errors and indexer problems as well as for compiler errors for generated sources  in the _Problem View_ of Eclipse.

I agree that specifying cmake cache variables for different build configurations may become painful, but cmake4eclipse provides the `-C` option to specify them.

**Comment by ToBoMi** [comment]
I want to say that I started using code - OSS (vscode/vscodium) for cmake based projects. (beeing sad about leaving eclipse - sure - and missing eclipse at many places)
I don't want to blame someone or something - I just want to take out pressure here that _currently_ I do not need this anymore.
Thanks @15knots!

**Comment by bw35** [comment]
> So you are actually asking to support the `--presets` arguments of cmake?

It would be very convenient if the plug would allow to specify or alter the cmake command line. This would allow for passing --preset= and other options not yet covered by the plugin.

**Comment by 15knots** [comment]
@bw35 Please file a separate issue for that.
