### ISSUE TITLE
Allow adding cmake command line arguments 

### ISSUE THREAD

**Issue by bw35** [15knots/cmake4eclipse#180]
CMake supports a vast number of command line options, but only a few of them are currently used by cmake4eclipse. It would be convenient and desirable to allow the user to modify the cmake command line issued by cmake4eclipse to take advantage of features not yet covered by cmake4eclipse.

 #175 discusses to add support of CMake presets to the plugin. Allowing the user to add --preset=xyz to the cmake command line provides a workaround until support for CMake presets gets integrated into cmake4eclipse.
Another scenario might be enabling or disabling warnings by the various -W options or to specify a --toolchain file.

A possible solution would be to add a text entry where the user can append arguments to the command line. Since manipulating the command line is considered an advanced option, the user must take care not to create conflicts with the parameters set by cmake4eclipse. An optional read-only text field of the entire command line could be helpful to see what's going on.

**Comment by 15knots** [comment]
> #175 discusses to add support of CMake presets to the plugin. Allowing the user to add --preset=xyz to the cmake command line provides a workaround until support for CMake presets 
 gets integrated into cmake4eclipse.

Adding an option to specify the preset makes sence. Adding a UI that presents the available presets for selection is currently out of scope of this plugin, its primary goal is to **run** cmake to make the build work. (Of course, contributions are welcome.)

> Another scenario might be enabling or disabling warnings by the various -W options or to specify a --toolchain file.

Warnings can be enabled on the workbench preference pages. Versions of cmake4eclipse prior to 4.0 allowed to specify these on a per-project level, but in practice it made no sence since the warning options are most of the time used only by CMakeLists.txt-developers.

> A possible solution would be to add a text entry where the user can append arguments to the command line.

I agree, adding a UI field to allow to specify arbitrary commandline arguments could be useful. At least, that work well in [Jenkins cmakebuilder-plugin](https://github.com/jenkinsci/cmakebuilder-plugin).

> Since manipulating the command line is considered an advanced option, the user must take care not to create conflicts with the parameters set by cmake4eclipse. An optional read-only text field of the entire command line could be helpful to see what's going on.

I don't think an extra display of the entire command line is necessary since the entire commandline is printed in the console view.

**Comment by bw35** [comment]
>Adding an option to specify the preset makes sence. Adding a UI that presents the available presets for selection is currently out of scope of this plugin, its primary goal is to run cmake to make the build work. (Of course, contributions are welcome.)

I don't expect anyone to add support to parse and display the contents of CMakePresets.json on the GUI. That's what CMake manual suggests in their [IDE integration guide](https://cmake.org/cmake/help/latest/guide/ide-integration/index.html#presets), but I'm more than happy if it's possible to specify the preset on the command line.

>Warnings can be enabled on the workbench preference pages. Versions of cmake4eclipse prior to 4.0 allowed to specify these on a per-project level, but in practice it made no sence since the warning options are most of the time used only by CMakeLists.txt-developers.

I noticed the presence of the warning options in the preferences just after I've issued the feature request. Using warning options as use case wasn't my smartest choice to advocate for a solution which allows arbitrary command line arguments, but you got the idea anyway :-)

>I don't think an extra display of the entire command line is necessary since the entire commandline is printed in the console view.

Agree, the information is already in the console. Putting it on the dialog isn't necessary but it would give WYSIWYG. The suggestion is inspired by the CDT managed build settings:

![image](https://user-images.githubusercontent.com/14139370/225257374-493b8388-9649-4236-96f5-da649933991f.png)

If you don't see any added value, simply ignore it.
