### ISSUE TITLE
Variable substitution for CMake executable

### ISSUE THREAD

**Issue by Carl2** [15knots/cmake4eclipse#36]
Setting the CMake executable under "Host OS override" to a variable for substitution does not work.

This is especially useful when using cross-compilation on multiple targets.

I.e:
Using c/c++ -> Enviroment
`$NATIVE_SYSROOT/usr/bin/cmake`
or
Shell enviroment
`${env_var:NATIVE_SYSROOT}/usr/bin/cmake`
or 
 $NATIVE_SYSROOT is a eclipse build variable (c/c++ -> Build Variable macro)

It would be great if that would be possible.

Cheers
Carl

**Comment by 15knots** [comment]
Instead of invoking a version of cmake which was compiled for cross-compilation, it might make more sense to use the already installed (latest and greatest :-) version of cmake and tell it to generate build-scripts that invoke cross-compilers by specifying a [toolchain file argument](https://cmake.org/cmake/help/v3.6/manual/cmake-toolchains.7.html#toolchain-features) to cmake, 
Values in the _Symbols_-tab support variable expansion.

**Comment by Carl2** [comment]
Excellent suggestion!
The problem lies in the environment since there are several teams working on the same targets, the easy way instead of managing every computers version of cmake ,they were handed a roots-fs (native and target via Yocto) with an pre-installed cmake which was then used for cross-compilation. That way the developers don't need to be bothered with the right version of cmake. 
That was the background. But your answer is still good since versioning check can be made in CMakelists.txt which gives the developer no other option then to install what ever version necessary.
Anyhow, I can live without the variable substitution, but if its an easy fix and you have the time it will be much appreciated.

Thanks
Carl
