### ISSUE TITLE
CMAKE_EXPORT_COMPILE_COMMANDS Parser should support different versions of compilers

### ISSUE THREAD

**Issue by radovanovic** [15knots/cmake4eclipse#43]
It is quite common if you have multiple versions of compiler for them to be installed with version as suffix (for example at the moment I have clang++, clang++35, clang++40, g++, g++5 and g++6). I am not sure about possible version suffixes (if it is possible to have say g++5.1 or it would always be g++51), but at the moment those compilers do not work well with cmake4eclipse.

Other than that this is really nice plugin (it is the only that gave me proper C++14 support in eclipse). Thanks for building it :-)

**Comment by 15knots** [comment]
Detection of the compiler -- which is required to parse its valid arguments -- is pattern based.
There is already a pattern to detect GCC cross compilers (see issue #33).
Unfortunately, the is no convention how compiler versions are to be specified, so adding a reliable pattern to detect different versions seems to be nearly impossible. For example, GCC 5 for openSuse has the name [gcc-5](http://fr2.rpmfind.net/linux/RPM/opensuse/updates/leap/42.2/oss/x86_64/gcc5-5.3.1+r233831-8.3.1.x86_64.html). 

The only way to implement this would be to add an option for end-users to disable the build-in patterns and allow specify the pattern they need.

**Comment by radovanovic** [comment]
This for end users to specify pattern they want would be the best possible solution (I don't know how difficult it would be to implement), but thinking about pattern I would allow suffix to contain dashes (minus), digits and dot (not sure if that can cause any damage to what you already have, and while it is true that g++1.7-2.3-4 can be whatever it is most likely that it is g++ compiler if it was listed in rules in CMakeLists). Again it is matter of judgement if this is really needed (probably not that many people keep different versions of compilers installed anyway).

**Comment by 15knots** [comment]
Specifying just a pattern to detect the compiler is insufficient, AFAICS. The parser also needs to know the type of compiler (gcc/clang, intel-compiler, ms-compiler, EDG compiler) to detect the arguments that specify an include directory.

I think this feature is rarely needed, Isn't the alternatives-mechanism supposed to handle this case (`man update-alternatives`)?

**Comment by radovanovic** [comment]
Re update-alternatives it is not really quite the same (I would be surprised if Linux is in this respect different from FreeBSD I am using): you have one system compiler which is used to build kernel and userland, and that one is considered part of OS and it is highly not recommended to change it to anything else (that is the one getting cc, c++ and others without number suffix). If you want to use some newer or different compiler you install that but that one will get version suffix. For example on FreeBSD 9 system compiler was gcc 4.2.1 which wasn't able to cope with newer C++ constructs so the only way to work with C++14 was to have additional compiler installed, and that one had number suffix.

Maybe it would be good idea if those compiler recognizing problems went somewhere within eclipse (so they could be seen from IDE, maybe in that warning pad) - I saw mine by pure accident (I was running eclipse with console logging enabled for completely different reason). Then people would see there is some problem with recognizing compiler and they could look for solution (this way they might think that plugin simply doesn't work).

**Comment by 15knots** [comment]
> Maybe it would be good idea if those compiler recognizing problems went somewhere within eclipse (so they could be seen from IDE, maybe in that warning pad

Agreed, as of 9cfd023d0702d7dcba746f866c2a0585e81136f9, problems go to Problems View instead of writing them to the application log file.

**Comment by Vlad-ll** [comment]
I still got no luck with this feature:
Description	Resource	Path	Location	Type
No parser for command '/apps/tools/cent_os72/binlinks/g++-7.1    -I/apps/tools/cent_os72/thirdparty/boost/boost_1_64_0/include -I/home/ven_vsolontsov/repositories/bepa/common/include  -g -Wall -pedantic -Wconversion -Wno-unused-parameter -std=gnu++1y -msse4.2   -o CMakeFiles/mlpsettings.dir/src/settings.cpp.o -c /home/ven_vsolontsov/repositories/bepa/common/settings/src/settings.cpp'. Your workbench will not know all include paths and preprocessor defines.	compile_commands.json	/bepa/build/Debug	Unknown	CMAKE_EXPORT_COMPILE_COMMANDS Parser Problem

I turned on the new option "Also try with version suffix" and even replaced suffix pattern to explicit version: -7\.1 (default pattern should work perfectly as well).

Could you advise please?

**Comment by 15knots** [comment]
I added a test for your case (516195d66a1a6fbabdbe83c197f37197062708c5) which is successful.
Could be caused by internal caching.
Does your project used different compilers?

**Comment by Vlad-ll** [comment]
No, I don't think it's about caching. Eclipse project is created from scratch in a new workspace, under a fresh instance of Eclipse with latest updates. Source tree also was clean (just cloned from git), with no generated files or whatever. 

So it was a relatively clean experiment.

/apps/tools/cent_os72/binlinks/g++-7.1 in my case is a soft link, but I don't think it may have any impact... Today g++-7.1 is hardcoded in CMakeList as the only compiler, but I'm going to add icc and clang a little bit later.

Anything I can check?

**Comment by 15knots** [comment]
The soft link should not matter.
You could try to empty the version field, which will reset it to the default. `-7.1` will not work, you have to specify `-7\.1`

**Comment by Vlad-ll** [comment]
Re "-7.1" -- well, both should work (with and without backslash). Initially I used "-7\.1".

Tried to catch the issue again... I managed to get a working project (p13 and below), but not sure what was wrong. And I'm not sure if the result is reproducible.

0. git clone -- CMakeLists.txt in the root
1. New / C++ Project / Executable / Empty project / Toolchain: Linux GCC
2. Checked "Generate Makefiles automatically" -- it's set by default
3. C/C++ Build / Tool Chain Editor -- set current builder to CMake Make Builder
4. Apply and Close
5. Build project
6. In Problems view -- nothing until I opened a source file; General / Path and Symbols -- nothing; In Project view / Includes it shows only system includes
7. Properties / Preprocessor Includes / Provides -- turn on CMAKE_EXPORT_COMPILE_COMMANDS Parser and "Also try with version suffix"
8. Unset CDT GCC Built-in Compiler Settings
9. Apply and close -- Includes disappeared from project view
10. Project clean; Project build
11. In Problems view got a set of "No parser for command"
---
12. After playing around -- moving Preprocessor Include providers up and down, changing providers, etc, I found that:
12.1. If I delete "No parser for command .." from Problems view, it doesn't appear (with CMAKE_EXPORT_COMPILE_COMMANDS turned on) until I re-open the project and rebuild. Simple rebuild / re-index doesn't bring it back, however indexing is still broken.
12.2. At some point it recognized paths to compiler's includes
--
13. I tried to re-create the proj once again: 
13.1. close proj; rm .settings .*project
13.2. New project as before but instead of finishing the wizard, pressed Advanced and configured things:
13.3. C/C++ Build / Tool Chain Editor -- set current builder to CMake Make Builder
13.4. Properties / Preprocessor Includes / Provides --turn on CMAKE_EXPORT_COMPILE_COMMANDS and moved it up, above CDT Managed Build Settings Entries; turned off CDT GCC Built-in Compiler Settings.
13.5. After applying these and building the project I got correct paths apart from system ones.
13.6. Turned on back again the provider "CDT GCC Built-in Compiler Settings" -- it added system includes and unnecessary default compiler's include. But as it's last, there's no impact.

Bad thing is that I see no Symbols parsed by CMAKE_EXPORT_COMPILE_COMMANDS. Built-In one has plenty of symbols but they are not always correct. E.g. __cplusplus is set to 199711L. I don't understand how Indexer recognizes c++14 STL features, but it does...

**Comment by Vlad-ll** [comment]
Update: after re-opening the project it lost 7.1 compiler includes from Project Explorer/ Includes. However Indexer still kept using them in existing files. Adding STL include into a translation unit which didn't have any STL leads to using default compiler's include :(.

**Comment by 15knots** [comment]
Well the Project Explorer/ Includes sometimes does not update properly. In any case, the indexer should be aware of the symbols/paths.

Anyway, the real problem is

> 11. In Problems view got a set of "No parser for command"

which indicates your compiler is not detected.
Is your project on github so I can give it a try?
Or could you post/attach the compile_commands.json file here?

@radovanovic What is your experience with this feature. Does it work for you? Can you help?

**Comment by radovanovic** [comment]
Sorry guys, I only now (by pure chance) noticed that I was mentioned before (I was receiving emails but I didn't notice someone was talking to me).

Everything worked for me, but now when I updated to latest version of plugin it seems like again it is not updating include paths correctly. However I am not receiving any errors. I will investigate code a little bit and see if that gives me some idea.

**Comment by radovanovic** [comment]
Sorry, stupid me - I didn't recompile project from eclipse, so plugin didn't have chance to read setting from that json file, when I did recompile everything worked as expected.

**Comment by radovanovic** [comment]
After some checking - I think there is error with regex https://github.com/15knots/cmake4eclipse/blob/a60683c3c093b2ab18cab1535e15387dea4afd4f/de.marw.cmake/src/main/java/de/marw/cmake/cdt/language/settings/providers/ParserDetection.java#L257

I think rather than "^(.*?/)??(" it should be "^[\\S/]*(" (as it is right now it allows max one / in compiler path, new version would allow any number of non-space characters and slashes - even better would be "^(?:[\\S/]|\\\\ )*(" to allow spaces if they have backslash in front of them, but I am not sure if I have right java syntax for non-capturing group there)

**Comment by radovanovic** [comment]
Please ignore previous comment, now I understand what your regex was doing (actually you wanted to capture everything up to the last slash) and you also wanted to allow compiler name without path. That regex is correct.

**Comment by radovanovic** [comment]
It works properly without version, both with full path to compiler and without path (ie /usr/bin/clang++ and clang++).

There is definitely something broken with version parsing, but I am quite sure it used to work when you fixed it last time, now if I use other version of compiler it fails parsing json file (and I get warnings like "No parser for command '/usr/local/bin/clang++40   -I/home/rivan/workspace/first/test/../utility -I/home/rivan/workspace/first/test/../include -I/home/rivan/workspace/first/test  -g   -std=c++1y -stdlib=libc++ -include-pch /home/rivan/workspace/first/build/Debug/test/catch.hpp.pch -include-pch /home/rivan/workspace/first/build/Debug/test/pch.hpp.pch -o CMakeFiles/first_test.dir/__/utility/fun.cpp.o -c /home/rivan/workspace/first/utility/fun.cpp'. Your workbench will not know all include paths and preprocessor defines.	compile_commands.json	/first/build/Debug	Unknown	CMAKE_EXPORT_COMPILE_COMMANDS Parser Problem")

Json file looks as expected:
`[
{
  "directory": "/home/rivan/workspace/first/build/Debug/test",
  "command": "/usr/local/bin/clang++40   -I/home/rivan/workspace/first/test/../utility -I/home/rivan/workspace/first/test/../include -I/home/rivan/workspace/first/test  -g   -std=c++1y -stdlib=libc++ -include-pch /home/rivan/workspace/first/build/Debug/test/catch.hpp.pch -include-pch /home/rivan/workspace/first/build/Debug/test/pch.hpp.pch -o CMakeFiles/first_test.test.dir/__/utility/fun.cpp.o -c /home/rivan/workspace/first/utility/fun.cpp",
  "file": "/home/rivan/workspace/first/utility/fun.cpp"
}...
`

Doesn't work no matter what I put in version field (I tried even simple "40").

**Comment by radovanovic** [comment]
One interesting thing - if I have enabled use version suffix and as suffix I have "40" (so it is mandatory suffix), it still properly parses clang++ without version (like it completely ignores these version settings). Maybe there is no problem with parsing code but with one communicating these settings with user?

**Comment by 15knots** [comment]
> One interesting thing - if I have enabled use version suffix and as suffix I have "40" (so it is mandatory suffix), it still properly parses clang++ without version

That's normal: It will try to match `clang++` first and take that if it matches,  In case of no match, it will then try to match with the version suffix.. 
Note the label on the checkbox saying _**Also** try with_ ...
So if your compiler is named `clang++`, it will match that regardless of the version suffix being enabled or not.

**Comment by 15knots** [comment]
I just added a unit test to match `/usr/local/bin/clang++40 ` with a version suffix of `40` and the test succeeds.
It also succeeds with the default version suffix `-?\d+(\.\d+)*`.
Do you use the per-project version-suffix-settings or the per-workspace-settings?

**Comment by radovanovic** [comment]
Hmmmm, once I clicked "use global provider" it started to work (now I am not receiving any errors and I can see include paths are correct) - now I am unable to go back to the state when it didn't work (even when I disable global provider it continues to work).

**Comment by 15knots** [comment]
Maybe, you hit some kind of the magic of how CDT stores settings;-)
I do not think it would make sense to investigate on magic, so please close this if you feel it works.

**Comment by radovanovic** [comment]
Yes, these are the days when miracles do happen ;-)

Have happy New Year!
