### ISSUE TITLE
Is it possible to make it instructing paths and symbols from generated Makefiles

### ISSUE THREAD

**Issue by Vlad-ll** [15knots/cmake4eclipse#45]
First of all, many thanks for you efforts.

I got a compilable project, so the build/clean works perfectly.
However, Eclipse Indexer doesn't resolve names and paths (I use non-default compiler specified in the root CMakeLists.txt and a number of libraries).
1. In "Path and Symbols" Symbols list is empty
2. In "Path and Symbols" Includes list is empty as well
3. "Preprocessor Include Paths, Macros, etc" contains a default set of include directories and default preprocessor symbols.

May be I created project somehow incorrectly:
- C/C++ Project
- Empty or Existing CMake Project

Please could you advise or plan an improvement?

**Comment by 15knots** [comment]
This plugin predates the cmake support provided by the CDT team and is made to work just with a plain _C/C++ Project_.

The _Empty or Existing CMake Project_ project creation dialog comes from the CDT team since CDT 9.1, it is not related to this plugin.

Just create a plain _C/C++ Project_ and enable the settings provider, which teaches CDT to recognize the preprocessor defines and include paths defined in your `CMakelists.txt`: Enable `Project  Properties|C/C++ General|Preprocessor include Paths...|Providers|CMAKE_EXPORT_COMPILE_COMMANDS Parser`). Of course, the name of your compiler executable file should match sth. like _gcc, cc_ or _gcc,.exe cc.exe_ for the parser to work. If not and if you do not see your include dirs displayed in the includes folder in the C-Projects view; check the error log of eclipse and report here.

As a start, you might check-out the the [test project here](https://github.com/15knots/cmake4eclipse/tree/master/testprojects/C-inclpaths) and use it as a template.

**Comment by Vlad-ll** [comment]
Seems like the issue is about "versioned" gcc name:
/test/build/Debug/compile_commands.json: No parser for command '/apps/tools/cent_os72/binlinks/g++-7.1 ....', skipped
Is it possible to tune it for recognizing g++-7.1  as g++?

**Comment by 15knots** [comment]
See issue #43.
