### ISSUE TITLE
Build output location does not support variable expansion.

### ISSUE THREAD

**Issue by Carl2** [15knots/cmake4eclipse#54]
Hi,
I'm trying to use a variable from the environment to set as my build path. But unfortunately this doesn't seem to be possible. The variable expansion doesn't seem to work in this field.

e.g 
Where [ ] is the input field
Build Output location
[` build_${OECORE_SDK_VERSION}` ] 

[ `build_${env_var:OECORE_SDK_VERSION} `]

It would be really great to have this :+1:

**Comment by 15knots** [comment]
Yes, it would be nice to have variable substitution there.
In fact it is already there, just a button to enter variables is missing.
If You enter variable expressions manually, you will notice, they get expanded., but are garbled in case the variable represents a path.  
Variable expansion is handled by code in the CDT project, consider to file a bug there.
See [here](https://www.google.de/search?q=%22gets+split+into+2+path+segments%22+CDT).

**Comment by 15knots** [comment]
Meanwhile, I found a way to expand variables before CDT gets a chance to expand them in a garbled fashion.
But that will be of limited use, since the actual build output location must be **below the project root,** otherwise, CDT``s debug configuration editor will not find your built executable. (To be more specific: The location has to be an Eclipse resource, a location below a linked folder moght satisfy your needs).

Please give feedback.
