### ISSUE TITLE
Make the Internal Package Pubic

### ISSUE THREAD

**Issue by jerroydmoore** [15knots/cmake4eclipse#75]
**This is a...**  

- [ ] Bug Report  
- [X] Enhancement Request

## Brief Description
I want to build on top of and eventually contribute towards the cmake4eclipse plugin

## (If Enhancement Request) Describe it. 
In order to run cmake4eclipse commands in a container, I would like to start with a solution build upon the internals package, improve upon it, and merge it back into cmake4eclipse. My time lines are quite long (measured in months), as I have other priorities, but this solution would be good enough for my immediate needs, and shippable in a month. Then, when I have more time, I can replace my docker management system with cdt's optional docker feature, and also replace the cmake4eclipse/docker integration with a more main stream version. But, for now, I simply need to make the internal pacakge publicly available, or I will fork my own cmake4eclipse, expose the internal package, and use this version, periodically pulling updates from this repo to maintain parity. 

## Useful Information
cmake4eclipse verssion: 1.11.1
Which OS do you use: Running Eclipse/cmake4eclipse on a MacOS Sierra V10.12.6 host, executing cmake/make commands in an ubuntu:xenial container.
Cmake version: 3.5.1

**Comment by 15knots** [comment]
Do you still need access to the internal package?
I don't think there is a reason for your own cmake4eclipse/docker integration anymore. As of commit 6f49eefac86d5dde789e9d656814e5fe35b1e311, the plugin is able to build inside a docker container with the official CDT docker support. This change was published plugin release 1.11.1.
Due to a bug in CDT's docker support reported on the [mailing list](https://groups.google.com/forum/#!searchin/cmake4eclipse-users/doser%7Csort:date/cmake4eclipse-users/fzetPJO8HK0/q7b3gD_lAgAJ), you will have to seclet the ninja generator, not the Unix Makefile generator. (Anyway, you will chose ninja, it builds much faster than make.)

**Comment by 15knots** [comment]
Closing this as building in docker containers has been implemented.
