### ISSUE TITLE
cmake not invoked when CMakeLists.txt changes

### ISSUE THREAD

**Issue by qwertie** [15knots/cmake4eclipse#98]
**This is a...**  
- [X] Bug Report  

## Brief Summary

After following steps detailed in #97 to create a project, I can't figure out how to cause cmake4eclipse to respond to changes in CMakeLists.txt; e.g. adding `message("HELLO THERE...")` seems to have no effect.

### What is the expected behavior?

Some indication that `cmake` was invoked, e.g. output of `cmake` in CDT build console.

### What behavior are you observing?

No sign that `cmake` was invoked.

### Provide the steps to reproduce the issue, if applicable:

1. In project properties, in `C/C++ Build | Environment` I added a `CC` environment variable. `cmake` was not invoked during next attempt to build.
2. In project properties, in `C/C++ Build | CMake` I checked "Force cmake to run with each build". I built. I cleaned. I built again. No effect.
3. I modified CMakeLists.txt, cleaned and rebuilt. No effect.
4. I unchecked "Force cmake to run with each build" again and modified CMakeLists.txt again. Still nothing.

## Useful Information

- cmake4eclipse version: Not sure, does "CDT CMake build integration" refer to cmake4eclipse? Because that component has version 1.12.2.201809221952.
- Which OS do you use: CentOS 7.2
- Cmake version: 3.11

**Comment by 15knots** [comment]
cmake4eclipse run cmake if you actually **build** the project.
If it does, you will find a console view named `CMake Console` where you can find cmakes 's output. The output is also printed to the `CDT global build console`.

My guess is that you configured your project to use CDTs new `core build system`. cmake4eclipse is around since 2013 and uses CDT's older `Managed Build System (MBS)`, so it won't kick in with your project.
If you saw all that  _All, Arduino, CMake, Make, Meson, Qt_ choices while setting up the project, you are on the `core build system` road (which has poor cmake support, IMHO).

**Comment by qwertie** [comment]
The manual didn't have instructions that mention the "Managed Build System" or how to choose it. I did not choose "core build system", I chose "C++ Project" and "Executable" like I was told to. So how do I choose MBS?

**Comment by 15knots** [comment]
Closing this as the documentation has been updated with the latest release.
To find signs that cmake has been invoked, watch the CDT global console view.
